# Your Discord bot token (Found at https://discord.com/developers/applications)
botToken: ""

# Your Discord bot client ID
clientId: ""

# Your Genius API client access token (Found at https://genius.com/developers)
geniusApiKey: ""

# The colour to use for embeds sent by the bot
embedColour: "#2B2D31"

# Whether analytics should be sent when starting the bot
# See https://github.com/NerdyTechy/Melody/wiki/Analytics
enableAnalytics: true

# Whether the bot should autocomplete search results
# Disable this if you're experiencing Unknown Interaction errors
enableAutocomplete: true

# Settings to control the bot's player and controller
player:
    # Leave VC when a song ends
    leaveOnEndDelay: 300000 # 5 minutes
    # Leave VC when a song is stopped
    leaveOnStopDelay: 300000 # 5 minutes
    # Leave VC when the channel is empty
    leaveOnEmptyDelay: 300000 # 5 minutes
    # Deafen bot while playing
    deafenBot: false

# Whether the logger should send messages to a Discord webhook
logEventsToWebhook:
    enabled: false
    webhookUrl: ""

# The emojis to be used in buttons for certain embeds
# See https://github.com/NerdyTechy/Melody/wiki/Using-Custom-Emojis
emojis:
    stop: "‚èπ"
    skip: "‚è≠"
    queue: "üìú"
    pause: "‚èØ"
    lyrics: "üìú"
    back: "‚èÆ"

# Make Melody use a proxy when making requests.
# Useful if you're experiencing 429 errors.
# See https://github.com/NerdyTechy/Melody/wiki/Proxying-Requests
# Omit user:pass@ if your proxy does not require authentication.
proxy:
    enable: false
    connectionUrl: "http://user:pass@111.111.111.111:8080"